from ctypes.test.test_pickling import name

'''To read a text file in Python, you follow these steps:

First, open a text file for reading by using the open() function.
Second, read text from the text file using the file read(), readline(), or readlines() method of the file object.
Third, close the file using the file close() method.
'''

'''The open() function has many parameters but you’ll be focusing on the first two.
The mode is an optional parameter. It’s a string that specifies the mode in which you want to open the file.
"r" is the mode and stands for Open for text file for reading text
; 'w' for Open a text file for writing text; 'W+' to write and read '''

openFile = open(r"C:\Users\ytiani\Downloads\Failed Payment Scenarios.txt", "r")

'''Realines to read as list then iterate in the list to print all the lines'''

readFiles = openFile.readlines()

print("\n the total line is {} \n" .format(len(readFiles)))

# readPerLines  = [print(x) for x in readFiles]
openFile.close()

############################################## Another way of reading file using with as statement ###########################
'''This is useful when you want to open the file as new file and so you don't get error when trying to close the file'''

#  with open(r"C:\Users\ytiani\Downloads\Failed Payment Scenarios.txt", "r") as newFile:
#     readFiles = newFile.readlines()
#     readPerLines  = [print(x) for x in readFiles]
#     newFile.close() 


###################################### Write and read file in python ###################
myList = ["One", "Two", "Three"];  
 
with open("C:\\Users\\ytiani\\Downloads\\File Generated By Python.txt", "w+") as f:
    for x in myList:       
        writeInFile = f.write(x + '\n');
f.close()

myList2 = ["Four", "Five", "Six"];         
with open("C:\\Users\\ytiani\\Downloads\\File Generated By Python.txt", "a") as f:
    for x in myList2:       
        writeInFile = f.write(x + '\n');
f.close()
    
    